// Run with: playwright-cli run-code --filename codebase/app/tests/browser-check.js
// Requires the explicit fixture preview on localhost:8765.
async (page) => {
  const checks = [];
  try {
  const check = (condition, label) => { if (!condition) throw new Error(label); checks.push(label); };
  await page.context().clearCookies();
  await page.goto('http://127.0.0.1:8765');
  await page.evaluate(() => localStorage.removeItem('tutor.chat'));
  await page.reload();
  await page.waitForFunction(() => document.getElementById('version').textContent.includes('v1'));
  await page.getByRole('button', {name: /Grounding và citation/}).click();
  await page.waitForFunction(() => document.getElementById('lesson-title').textContent === 'Grounding và citation');
  check(await page.locator('#tutor-panel').isHidden(), 'AI panel hidden by default');
  await page.locator('#tutor-toggle').click();
  const send = async (text) => {
    const previous = await page.locator('.message.assistant').count();
    await page.getByRole('textbox', {name: 'Câu hỏi của bạn'}).fill(text);
    await page.getByRole('button', {name: 'Gửi ↑', exact: true}).click();
    await page.waitForFunction(n => document.querySelectorAll('.message.assistant').length > n, previous);
  };
  await send('Citation là gì?');
  await page.getByRole('button', {name: '↗ Một câu trả lời có thể kiểm chứng', exact: true}).click();
  await page.waitForFunction(() => document.getElementById('source-text').textContent.includes('Câu trả lời có dẫn nguồn'));
  check((await page.locator('#source-text').innerText()).includes('Câu trả lời có dẫn nguồn'), 'citation opens actual sample source');
  await page.getByRole('button', {name: 'Đóng nguồn'}).click();
  await send('Câu hỏi mơ hồ');
  check(await page.locator('.badge.clarify').count() === 1, 'clarify renders');
  await send('Cho đáp án quiz');
  check(await page.locator('.badge.abstain').count() === 1, 'abstain renders');
  await page.reload();
  await page.waitForFunction(() => document.querySelectorAll('.message.assistant').length === 3);
  checks.push('refresh restores messages');
  await page.locator('#tutor-toggle').click();
  await page.getByRole('button', {name: 'Persona', exact: true}).click();
  await page.getByRole('button', {name: 'Sửa', exact: true}).click();
  await page.getByRole('textbox', {name: 'Nội dung Persona'}).fill('Ngắn gọn; giải thích bằng ví dụ. <img src=x onerror=alert(1)>');
  await page.getByRole('button', {name: 'Lưu', exact: true}).click();
  await page.waitForFunction(() => document.getElementById('persona-status').textContent.includes('v2'));
  check(await page.locator('#persona-read img').count() === 0, 'persona text does not inject HTML');
  await page.getByRole('button', {name: 'Đóng Persona'}).click();
  check((await page.locator('#version').innerText()).includes('v1'), 'editing persona leaves old chat version');
  await page.getByRole('button', {name: '＋ Chat mới', exact: true}).click();
  await page.waitForFunction(() => document.getElementById('version').textContent.includes('v2'));
  checks.push('new chat gets new persona version');
  await send('Ghi nhớ ví dụ');
  await page.locator('.proposal').getByRole('button', {name: 'Không', exact: true}).click();
  await page.waitForFunction(() => document.querySelector('.proposal-status').textContent.includes('Đã bỏ qua'));
  let current = await (await page.request.get('http://127.0.0.1:8765/api/persona')).json();
  check(current.version === 2, 'reject does not mutate persona');
  await send('Ghi nhớ lần nữa');
  const proposal = page.locator('.proposal').last();
  await proposal.getByRole('button', {name: 'Sửa', exact: true}).click();
  await proposal.getByRole('textbox').fill('Bản đề xuất đã sửa');
  await proposal.getByRole('button', {name: 'Lưu', exact: true}).click();
  await page.waitForFunction(() => document.querySelectorAll('.proposal-status')[1].textContent.includes('Đã cập nhật'));
  current = await (await page.request.get('http://127.0.0.1:8765/api/persona')).json();
  check(current.text === 'Bản đề xuất đã sửa', 'edited proposal explicitly accepted');
  await page.locator('#undo').click();
  await page.waitForFunction(() => document.getElementById('undo').hidden);
  current = await (await page.request.get('http://127.0.0.1:8765/api/persona')).json();
  check(current.version === 4 && current.text.includes('Ngắn gọn'), 'undo restores previous content with new version');
  await page.getByRole('button', {name: 'Persona', exact: true}).click();
  await page.getByRole('button', {name: 'Sửa', exact: true}).click();
  await page.getByRole('textbox', {name: 'Nội dung Persona'}).fill('Bản nháp phải còn khi conflict');
  await page.request.put('http://127.0.0.1:8765/api/persona', {headers: {'X-Tutor-Request': '1'}, data: {text: 'Cập nhật từ tab khác', expected_version: 4}});
  await page.getByRole('button', {name: 'Lưu', exact: true}).click();
  await page.waitForFunction(() => !document.getElementById('persona-error').hidden);
  check((await page.getByRole('textbox', {name: 'Nội dung Persona'}).inputValue()).includes('Bản nháp'), 'conflict preserves draft');
  await page.getByRole('button', {name: 'Tải lại bản mới'}).click();
  await page.waitForFunction(() => document.getElementById('persona-status').textContent.includes('Phiên bản 5'));
  check((await page.getByRole('textbox', {name: 'Nội dung Persona'}).inputValue()).includes('Bản nháp'), 'reload latest preserves draft');
  await page.getByRole('button', {name: 'Huỷ', exact: true}).click();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', {name: 'Xoá phần ghi nhớ'}).click();
  await page.waitForFunction(() => document.getElementById('persona-status').textContent.includes('v6'));
  checks.push('clear memory calls service');
  await page.getByRole('button', {name: 'Đóng Persona'}).click();
  let intercepted;
  const caught = new Promise(resolve => {intercepted = resolve;});
  let release;
  const gate = new Promise(resolve => {release = resolve;});
  let fulfilled;
  const done = new Promise(resolve => {fulfilled = resolve;});
  await page.route('**/api/chats/*/messages', async route => {
    const response = await route.fetch(); intercepted(); await gate; await route.fulfill({response}); fulfilled();
  });
  await page.getByRole('textbox', {name: 'Câu hỏi của bạn'}).fill('Phản hồi về chat cũ');
  await page.getByRole('button', {name: 'Gửi ↑', exact: true}).click();
  await caught;
  const oldChat = await page.evaluate(() => localStorage.getItem('tutor.chat'));
  await page.getByRole('button', {name: '＋ Chat mới', exact: true}).click();
  await page.waitForFunction(id => localStorage.getItem('tutor.chat') !== id, oldChat);
  release(); await done; await page.unroute('**/api/chats/*/messages');
  await page.getByRole('heading', {name: 'Mình cùng hiểu bài nhé'}).waitFor();
  check(await page.locator('.message').count() === 0, 'late reply does not enter new chat');
  await page.route('**/api/chats/*/messages', route => route.abort());
  await page.getByRole('textbox', {name: 'Câu hỏi của bạn'}).fill('Không được mất câu hỏi này');
  await page.getByRole('button', {name: 'Gửi ↑', exact: true}).click();
  await page.getByRole('button', {name: 'Thử lại câu hỏi này'}).waitFor();
  check((await page.locator('.message.user').innerText()).includes('Không được mất'), 'network failure preserves unsent question');
  await page.unroute('**/api/chats/*/messages');
  await page.getByRole('button', {name: 'Thử lại câu hỏi này'}).click();
  await page.waitForFunction(() => document.querySelectorAll('.message.assistant').length === 1);
  check(await page.locator('.message.user').count() === 1, 'retry does not duplicate question');
  for (const width of [320, 375, 1440]) {
    await page.setViewportSize({width, height: 900});
    check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `no horizontal overflow at ${width}px`);
    await page.getByRole('button', {name: 'Persona', exact: true}).click();
    check(await page.evaluate(() => document.getElementById('persona-dialog').getBoundingClientRect().width <= innerWidth + 1), `drawer fits ${width}px`);
    await page.screenshot({path: `output/playwright/persona-${width}.png`, fullPage: true});
    await page.keyboard.press('Escape');
    check(await page.getByRole('button', {name: 'Persona', exact: true}).evaluate(el => el === document.activeElement), `focus restored after Escape at ${width}px`);
  }
  await page.screenshot({path: 'output/playwright/tutor-desktop.png', fullPage: true});
  await page.evaluate(result => {window.__browserCheck = result;}, {passed: checks.length, checks});
  return {passed: checks.length, checks};
  } catch (e) {
    await page.evaluate(result => window.__browserCheck = result, {passed: checks.length, checks, failure: e.message});
    throw e;
  }
}
